# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OEMR
email: info@oemr.org
description: > # this means to ignore newlines until "baseurl:"
    OEMR is a non-profit (501(c)(3)) organization formed to ensure that all people, regardless of race, socioeconomic status or geographic location, have access to high-quality medical care through the donation of free, open source medical software and service
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oemr.org" # the base hostname & protocol for your site
twitter_username: oemr
github_username:  oemr501c3

# Build settings
markdown: kramdown
